version: '3.7'
services:
  web_app:
    image: nginx 
    ports:
      -  8000:80
    
    # render the index file from the src into the html file inside of nginx 
    volumes:
      - ./src:/usr/share/nginx/html
    
